#include "kq_candidate2.hpp"

#include <algorithm>
#include <array>
#include <cctype>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>

namespace {
using namespace omega_v2_1;
constexpr int kD = 512;
constexpr DWORD kFrozenCpuSetIds[4] = {266,264,258,270};

struct Series { std::vector<double> seconds; std::vector<std::uint64_t> allocations; std::uint64_t macs=0; double median_seconds=0.0; double median_rate=0.0; };
struct FullResult { Series timing; std::vector<float> last_state; bool finite=false; bool checksum_stable=false; };

double median(std::vector<double> values){std::sort(values.begin(),values.end());const auto i=values.size()/2;return (values.size()&1u)?values[i]:(values[i-1]+values[i])*0.5;}
std::string env_utf8(const wchar_t* name){std::vector<wchar_t>b(32768,L'\0');const DWORD n=GetEnvironmentVariableW(name,b.data(),static_cast<DWORD>(b.size()));if(n==0||n>=b.size())return{};const int need=WideCharToMultiByte(CP_UTF8,0,b.data(),-1,nullptr,0,nullptr,nullptr);if(need<=1)return{};std::string s(static_cast<std::size_t>(need),'\0');WideCharToMultiByte(CP_UTF8,0,b.data(),-1,s.data(),need,nullptr,nullptr);s.resize(static_cast<std::size_t>(need-1));return s;}
std::vector<double> parse_csv(const std::string& text){std::vector<double> out;std::stringstream s(text);std::string item;while(std::getline(s,item,','))if(!item.empty())out.push_back(std::stod(item));return out;}
std::uint64_t checksum_floats_kq2(const float* x,std::size_t n){std::uint64_t h=1469598103934665603ull;for(std::size_t i=0;i<n;++i){std::uint32_t b=0;std::memcpy(&b,x+i,sizeof(b));for(int j=0;j<4;++j){h^=static_cast<std::uint8_t>(b>>(8*j));h*=1099511628211ull;}}return h;}
bool finite_vector(const std::vector<float>& x){return std::all_of(x.begin(),x.end(),[](float v){return std::isfinite(v);});}
std::string read_text_file(const std::filesystem::path& path){std::ifstream input(path,std::ios::binary);if(!input)throw std::runtime_error("candidate_02 required baseline artifact missing: "+path.string());std::ostringstream text;text<<input.rdbuf();return text.str();}
std::string extract_json_object(const std::string& json,const std::string& key){const std::string token="\""+key+"\":";const std::size_t marker=json.find(token);if(marker==std::string::npos)throw std::runtime_error("candidate_02 baseline JSON missing object: "+key);const std::size_t begin=json.find('{',marker+token.size());if(begin==std::string::npos)throw std::runtime_error("candidate_02 baseline JSON malformed object: "+key);int depth=0;bool quoted=false,escaped=false;for(std::size_t i=begin;i<json.size();++i){const char c=json[i];if(quoted){if(escaped)escaped=false;else if(c=='\\')escaped=true;else if(c=='\"')quoted=false;continue;}if(c=='\"'){quoted=true;continue;}if(c=='{')++depth;else if(c=='}'&&--depth==0)return json.substr(begin,i-begin+1);}throw std::runtime_error("candidate_02 baseline JSON unterminated object: "+key);}
double extract_json_number(const std::string& json,const std::string& key){const std::string token="\""+key+"\":";const std::size_t marker=json.find(token);if(marker==std::string::npos)throw std::runtime_error("candidate_02 baseline JSON missing number: "+key);const std::size_t begin=marker+token.size();std::size_t end=begin;while(end<json.size()&&(std::isdigit(static_cast<unsigned char>(json[end]))||json[end]=='-'||json[end]=='+'||json[end]=='.'||json[end]=='e'||json[end]=='E'))++end;if(end==begin)throw std::runtime_error("candidate_02 baseline JSON malformed number: "+key);return std::stod(json.substr(begin,end-begin));}
std::vector<float> fixed_state(int m){std::vector<float>x(static_cast<std::size_t>(m)*kD);for(std::size_t i=0;i<x.size();++i){const int v=static_cast<int>((i*37+static_cast<std::size_t>(kD+m))%127)-63;x[i]=static_cast<float>(v)*(1.0f/256.0f);}return x;}
CoreWeights load_weights(const std::filesystem::path& path){std::ifstream in(path,std::ios::binary);if(!in)throw std::runtime_error("candidate_02 FP32 source-weight stream missing");constexpr std::array<std::pair<int,int>,7> dims={{{kD,kD},{kD,kD},{kD,kD},{kD,kD},{4*kD,kD},{4*kD,kD},{kD,4*kD}}};CoreWeights w;w.d=kD;Q4Matrix* target[]={&w.W_Q,&w.W_K,&w.W_V,&w.W_O,&w.W_gate,&w.W_up,&w.W_down};for(std::size_t i=0;i<dims.size();++i){auto [r,c]=dims[i];std::vector<float> v(static_cast<std::size_t>(r)*c);in.read(reinterpret_cast<char*>(v.data()),static_cast<std::streamsize>(v.size()*sizeof(float)));if(!in)throw std::runtime_error("candidate_02 FP32 weight stream truncated");target[i]->pack(v,r,c);w.logical_weight_bytes+=target[i]->packed.logical_bytes;w.logical_scale_bytes+=target[i]->scales_fp16.logical_bytes;w.alignment_padding_bytes+=target[i]->alignment_padding_bytes;w.physical_buffer_bytes+=target[i]->packed.allocated_bytes+target[i]->scales_fp16.allocated_bytes;}if(in.peek()!=std::ifstream::traits_type::eof())throw std::runtime_error("candidate_02 FP32 weight stream has trailing bytes");return w;}
void write_float_file(const std::filesystem::path& p,const std::vector<float>& v){std::ofstream o(p,std::ios::binary|std::ios::trunc);if(!o)throw std::runtime_error("candidate_02 cannot write native output file");o.write(reinterpret_cast<const char*>(v.data()),static_cast<std::streamsize>(v.size()*sizeof(float)));o.close();if(!o)throw std::runtime_error("candidate_02 native output write failed");}
void write_dequant(const CoreWeights& w,const std::filesystem::path& p){std::ofstream o(p,std::ios::binary|std::ios::trunc);if(!o)throw std::runtime_error("candidate_02 cannot write transient dequant comparison data");const Q4Matrix* ms[]={&w.W_Q,&w.W_K,&w.W_V,&w.W_O,&w.W_gate,&w.W_up,&w.W_down};for(const auto* m:ms)for(int r=0;r<m->rows;++r)for(int c=0;c<m->cols;++c){const float x=m->dequant_at(r,c);o.write(reinterpret_cast<const char*>(&x),sizeof(x));}o.close();if(!o)throw std::runtime_error("candidate_02 dequant comparison write failed");}
std::uint64_t l1d_size(const HardwareInfo& hw,DWORD id){const CpuSetRecord* selected=nullptr;for(const auto& core:hw.cores)for(const auto& cpu:core.cpu_sets)if(cpu.id==id)selected=&cpu;if(!selected)return 0;const KAFFINITY bit=static_cast<KAFFINITY>(1)<<selected->logical_index;std::uint64_t size=0;for(const auto& c:hw.caches)if(c.level==1&&c.type==CacheData)for(const auto& mask:c.group_masks)if(mask.first==selected->group&&(mask.second&bit))size=(std::max)(size,static_cast<std::uint64_t>(c.size_bytes));return size;}
std::string workers_json(const std::vector<CoreRecord>& ws){std::ostringstream o;o<<'[';for(std::size_t i=0;i<ws.size();++i){if(i)o<<',';const auto&w=ws[i];o<<"{\"worker_id\":"<<i<<",\"cpu_set_id\":"<<w.cpu_sets.front().id<<",\"logical_processor_id\":"<<static_cast<unsigned>(w.cpu_sets.front().logical_index)<<",\"physical_core_id\":"<<static_cast<unsigned>(w.core_index)<<",\"shard_weight\":"<<w.v_i<<'}';}o<<']';return o.str();}
std::string series_json(const Series&s){std::ostringstream o;o.precision(17);o<<"{\"warmups\":10,\"repetitions\":"<<s.seconds.size()<<",\"macs_per_sample\":"<<s.macs<<",\"median_seconds\":"<<s.median_seconds<<",\"median_macs_per_second\":"<<s.median_rate<<",\"timed_heap_allocations\":[";for(std::size_t i=0;i<s.allocations.size();++i){if(i)o<<',';o<<s.allocations[i];}o<<"],\"sample_seconds\":[";for(std::size_t i=0;i<s.seconds.size();++i){if(i)o<<',';o<<s.seconds[i];}o<<"]}";return o.str();}
std::string series_field(const char*n,const Series&s){return std::string("\"")+n+"\":"+series_json(s);}

Series measure_h0(const CoreWeights&w,int m,WorkerPool&pool,DWORD line){auto x=fixed_state(m);std::vector<float>y(x.size());const auto macs=static_cast<std::uint64_t>(m)*kD*kD;for(int i=0;i<10;++i){touch_weights(w,line);q4_linear(w.W_Q,x.data(),y.data(),m,pool);}Series s;s.macs=macs;s.seconds.reserve(31);s.allocations.reserve(31);for(int i=0;i<31;++i){touch_weights(w,line);begin_timed_allocation_count();const auto a=qpc_ticks();q4_linear(w.W_Q,x.data(),y.data(),m,pool);const auto b=qpc_ticks();const auto n=end_timed_allocation_count();if(b<=a||!pool.affinity_intact())throw std::runtime_error("candidate_02 H0 QPC/affinity invalid");s.seconds.push_back(static_cast<double>(b-a)/qpc_frequency());s.allocations.push_back(n);}s.median_seconds=median(s.seconds);s.median_rate=static_cast<double>(macs)/s.median_seconds;return s;}
FullResult measure_full(const CoreWeights&w,int m,int K,WorkerPool&pool,DWORD line){Scratch s;s.resize_for(kD,m);const auto init=fixed_state(m);const auto macs=static_cast<std::uint64_t>(K)*(16ull*m*kD*kD+2ull*m*m*kD);auto reset=[&]{std::copy(init.begin(),init.end(),s.state.begin());};auto go=[&]{for(int r=0;r<K;++r)v2_full_block_round(w,s,pool);};for(int i=0;i<10;++i){reset();touch_weights(w,line);go();}FullResult z;z.timing.macs=macs;z.timing.seconds.reserve(31);z.timing.allocations.reserve(31);std::uint64_t first=0,last=0;for(int i=0;i<31;++i){reset();touch_weights(w,line);begin_timed_allocation_count();const auto a=qpc_ticks();go();const auto b=qpc_ticks();const auto n=end_timed_allocation_count();if(b<=a||!pool.affinity_intact())throw std::runtime_error("candidate_02 FULL QPC/affinity invalid");z.timing.seconds.push_back(static_cast<double>(b-a)/qpc_frequency());z.timing.allocations.push_back(n);z.last_state=s.state;if(i==0)first=checksum_floats_kq2(s.state.data(),s.state.size());last=checksum_floats_kq2(s.state.data(),s.state.size());if(!finite_vector(s.state))throw std::runtime_error("candidate_02 FULL non-finite output");}reset();touch_weights(w,line);go();z.finite=finite_vector(s.state);z.checksum_stable=first==last&&last==checksum_floats_kq2(s.state.data(),s.state.size());z.timing.median_seconds=median(z.timing.seconds);z.timing.median_rate=static_cast<double>(macs)/z.timing.median_seconds;return z;}
void write_json(const std::filesystem::path&p,const std::string&s){std::ofstream o(p,std::ios::binary|std::ios::trunc);if(!o)throw std::runtime_error("candidate_02 cannot write KQ JSON");o<<s<<'\n';o.close();if(!o)throw std::runtime_error("candidate_02 failed writing KQ JSON");}

} // namespace

int main(int argc,char**argv){using namespace omega_v2_1;if(argc!=3||std::string(argv[1])!="--run-kq2")return 2;try{const auto exe=std::filesystem::absolute(argv[0]);const auto unit=exe.parent_path().parent_path().parent_path();const auto base=unit.parent_path()/"omega_v2_1b_kernel_qualification"/"results"/"omega_v2_1b_kernel_qualification";const auto root=std::filesystem::path(env_utf8(L"OMEGA_V2_1B_KQ2_RESULTS_ROOT"));const auto candidate=root.parent_path();const bool candidate_root=candidate.parent_path()==base&&candidate.filename()=="candidate_02"&&(root.filename()=="candidate_02"||root.filename()=="run_01");if(!root.is_absolute()||!candidate_root)throw std::runtime_error("candidate_02 KQ result path is outside its immutable result slot");std::filesystem::create_directories(root);if(std::filesystem::exists(root/"native_kq_candidate_02.json"))throw std::runtime_error("candidate_02 KQ native output already exists");
HardwareInfo hw;std::string error;if(!query_hardware(hw,error))throw std::runtime_error("candidate_02 topology failed: "+error);if(hw.cpu_model.find("i7-13700F")==std::string::npos||!hw.avx2||!hw.fma)throw std::runtime_error("candidate_02 requires the i7-13700F AVX2/FMA host");const auto weights_shard=parse_csv(env_utf8(L"OMEGA_V2_1B_KQ2_SHARD_WEIGHTS"));if(weights_shard.size()!=4)throw std::runtime_error("candidate_02 needs frozen H0 shard weights");std::vector<CoreRecord> workers;for(std::size_t i=0;i<4;++i){auto core=std::find_if(hw.cores.begin(),hw.cores.end(),[&](const CoreRecord&c){return std::any_of(c.cpu_sets.begin(),c.cpu_sets.end(),[&](const CpuSetRecord&cpu){return cpu.id==kFrozenCpuSetIds[i];});});if(core==hw.cores.end()||!core->classified_p_core)throw std::runtime_error("candidate_02 fixed CPU-set is not a P-core");CoreRecord w=*core;auto cpu=std::find_if(w.cpu_sets.begin(),w.cpu_sets.end(),[&](const CpuSetRecord&c){return c.id==kFrozenCpuSetIds[i];});CpuSetRecord one=*cpu;one.shard_weight=weights_shard[i];w.cpu_sets.assign(1,one);w.v_i=one.shard_weight;workers.push_back(std::move(w));}
const CpuSetRecord* coordinator=nullptr;for(const CoreRecord&c:hw.cores)if(c.intel_core_type==0x20&&c.cpu_sets.size()==1&&(!coordinator||c.cpu_sets.front().id<coordinator->id))coordinator=&c.cpu_sets.front();if(!coordinator||!set_current_cpu_set(coordinator->id,coordinator->group,coordinator->logical_index,error))throw std::runtime_error("candidate_02 E-core coordinator pin failed");hw.coordinator_cpu_set_id=coordinator->id;hw.coordinator_group=coordinator->group;hw.coordinator_logical_index=coordinator->logical_index;
const auto weight_source_sha=env_utf8(L"OMEGA_V2_1B_KQ2_SOURCE_WEIGHT_SHA256");const auto attempt02_sha=env_utf8(L"OMEGA_V2_1B_KQ2_ATTEMPT02_MANIFEST_SHA256");const auto candidate01_sha=env_utf8(L"OMEGA_V2_1B_KQ2_CANDIDATE01_MANIFEST_SHA256");const auto baseline_path=env_utf8(L"OMEGA_V2_1B_KQ2_CANDIDATE01_NATIVE_JSON");const auto dequant_path=env_utf8(L"OMEGA_V2_1B_KQ2_DEQUANT_PATH");const auto output_dir=env_utf8(L"OMEGA_V2_1B_KQ2_OUTPUTS_DIR");if(weight_source_sha.size()!=64||attempt02_sha.size()!=64||candidate01_sha.size()!=64||baseline_path.empty()||dequant_path.empty()||output_dir.empty())throw std::runtime_error("candidate_02 source provenance or controls incomplete");const std::string baseline_json=read_text_file(baseline_path);const std::string fma_json=extract_json_object(baseline_json,"fma_l1");const std::string fma_series=extract_json_object(fma_json,"series");const double p_fma=extract_json_number(fma_series,"median_macs_per_second");const std::string baseline_machine=extract_json_object(baseline_json,"machine_balance_diagnostic");const std::string dram_series=extract_json_object(baseline_machine,"dram_stream");const double bw=extract_json_number(baseline_machine,"BW_DRAM_bytes_per_second");const double dram_bytes=extract_json_number(baseline_machine,"dram_working_set_bytes");const double dram_minimum=extract_json_number(baseline_machine,"minimum_working_set_bytes");if(p_fma<=0||bw<=0||dram_bytes<4.0*hw.llc_bytes)throw std::runtime_error("candidate_02 candidate01 FMA/DRAM baseline is invalid");const CoreWeights weights=load_weights(argv[2]);if(weights.d!=kD)throw std::runtime_error("candidate_02 FP32 source weights must be d512");
WorkerPool pool({workers[0].cpu_sets.front(),workers[1].cpu_sets.front(),workers[2].cpu_sets.front(),workers[3].cpu_sets.front()});const std::string toy=full_block_scalar_reference_test(pool);if(toy.find("\"pass\":true")==std::string::npos)throw std::runtime_error("candidate_02 scalar-reference or exp-approx correctness failed before timing");const Series h0m1=measure_h0(weights,1,pool,hw.cache_line_bytes),h0m4=measure_h0(weights,4,pool,hw.cache_line_bytes),h0m16=measure_h0(weights,16,pool,hw.cache_line_bytes);const FullResult fm1=measure_full(weights,1,1,pool,hw.cache_line_bytes),fm4=measure_full(weights,4,1,pool,hw.cache_line_bytes),fm16=measure_full(weights,16,1,pool,hw.cache_line_bytes),fm8k4=measure_full(weights,8,4,pool,hw.cache_line_bytes);const bool affinity_ok=pool.affinity_intact();pool.stop();
const std::filesystem::path outputs(output_dir);std::filesystem::create_directories(outputs);write_float_file(outputs/"candidate2_full_m4_k1.bin",fm4.last_state);write_float_file(outputs/"candidate2_full_m16_k1.bin",fm16.last_state);write_float_file(outputs/"candidate2_full_m8_k4.bin",fm8k4.last_state);write_dequant(weights,dequant_path);
const double eq4=h0m16.median_rate/p_fma,ef4=fm4.timing.median_rate/h0m4.median_rate,ef16=fm16.timing.median_rate/h0m16.median_rate;const double ai4=static_cast<double>(16ull*4*kD*kD+2ull*4*4*kD)/weights.physical_buffer_bytes;const double m_machine=fm4.timing.median_rate/bw;const double rho_opt=1.0/(1.0+m_machine/ai4);const auto reuse_probe=omega_v2_1b_candidate_02::probe_dequant_tile_reuse(weights.W_Q,16);
std::ostringstream out;out.precision(17);out<<"{\"schema\":\"omega-v2-1b-native-kq-v1\",\"status\":\"KQ_NATIVE_COMPLETE\",\"candidate_id\":\"KQ2_ROW_TILE4_SLOT2_FUSED\",\"compile_candidate_id\":\"KQ2_ROW_TILE4_SLOT2_FUSED\""
<<",\"source_weight_sha256\":\""<<weight_source_sha<<"\",\"candidate01_manifest_sha256\":\""<<candidate01_sha<<"\",\"attempt02_manifest_sha256\":\""<<attempt02_sha<<"\""
<<",\"hardware\":"<<hardware_json(hw)<<",\"selected_workers\":"<<workers_json(workers)<<",\"qpc_frequency\":"<<qpc_frequency()
<<",\"scratch_per_worker_bytes\":"<<omega_v2_1b_candidate_02::kCandidateScratchBytesPerWorker<<",\"row_tile\":4,\"slot_tile\":2,\"fused_dispatches_per_round\":4"
<<",\"persistent_weight_format\":\"signed symmetric Q4 + FP16 group32 scales only\",\"predequantized_weight_copy_persistent\":false"
<<",\"fma_l1\":"<<fma_json
<<",\"dequant_exp_approximation\":{\"method\":\"range-reduced degree-7 Taylor exp with AVX2/FMA and reciprocal refinement\",\"domain\":[-80,80],\"relative_error_bound\":2e-6,\"dense_grid_check\":"<<toy<<'}'
<<",\"h0_q4\":{"<<series_field("m1",h0m1)<<','<<series_field("m4",h0m4)<<','<<series_field("m16",h0m16)<<'}'
<<",\"full_resident\":{"<<series_field("m1_k1",fm1.timing)<<','<<series_field("m4_k1",fm4.timing)<<','<<series_field("m16_k1",fm16.timing)<<','<<series_field("m8_k4_for_s_native",fm8k4.timing)
<<",\"full_outputs_finite\":"<<((fm4.finite&&fm16.finite&&fm8k4.finite)?"true":"false")<<",\"full_checksums_repeatable\":"<<((fm4.checksum_stable&&fm16.checksum_stable)?"true":"false")<<"}"
<<",\"correctness\":{\"toy_d32_m4_k2\":"<<toy<<",\"full_d512_outputs_finite\":"<<((fm4.finite&&fm16.finite&&fm8k4.finite)?"true":"false")<<",\"full_checksum_stable\":"<<((fm4.checksum_stable&&fm16.checksum_stable)?"true":"false")<<"}"
<<",\"dequant_tile_reuse\":{\"Q_W_m16\":{\"expected_groups\":"<<reuse_probe.expected_groups<<",\"observed_groups_per_call\":"<<reuse_probe.observed_groups<<",\"slots_reusing_each_row_tile\":"<<reuse_probe.slots_reused<<",\"pass\":"<<(reuse_probe.pass?"true":"false")<<"},\"scratch_per_worker_bytes\":"<<omega_v2_1b_candidate_02::kCandidateScratchBytesPerWorker<<"}"
<<",\"efficiencies\":{\"E_Q4\":"<<eq4<<",\"E_FULL_4\":"<<ef4<<",\"E_FULL_16\":"<<ef16<<"}"
<<",\"machine_balance_diagnostic\":{\"dram_stream\":"<<dram_series<<",\"dram_working_set_bytes\":"<<dram_bytes<<",\"minimum_working_set_bytes\":"<<dram_minimum<<",\"BW_DRAM_bytes_per_second\":"<<bw<<",\"physical_q4_core_bytes\":"<<weights.physical_buffer_bytes<<",\"AI_m4_MAC_per_byte\":"<<ai4<<",\"M_machine_MAC_per_byte\":"<<m_machine<<",\"rho_optimistic\":"<<rho_opt<<",\"affinity_ok\":"<<(affinity_ok?"true":"false")<<",\"source\":\"candidate_01 immutable KQ DRAM stream baseline\"}"
<<",\"kq_scope\":{\"abc_untimed_correctness_executed\":false,\"a_b_c_executed\":false,\"attempt03_executed\":false}}";write_json(root/"native_kq_candidate_02.json",out.str());std::cout<<out.str()<<'\n';return 0;
}catch(const std::exception&e){std::cerr<<"candidate_02 KQ native error: "<<e.what()<<'\n';return 3;}}
