import hashlib,json
from pathlib import Path
import torch
from nb5_fresh import NB5GateOnlyEncoder
from ctrl2_common import load_executor
from evaluate_u0c_c1_e_r_alu import VALUE_BASE,VALUE_COUNT
R=Path(__file__).resolve().parents[1];M=R/'campaign/nb5_manifests/manifest_6801_v2.json';A=R/'campaign/nb5_stage_a_6801/stage_a.pt';G=R/'campaign/nb5_stage_b_6801/gate.pt';O=R/'campaign/nb5_p_6801_reverse_v2'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 m=json.loads(M.read_text());a=torch.load(A,map_location='cpu',weights_only=False);g=torch.load(G,map_location='cpu',weights_only=False);e=NB5GateOnlyEncoder(a['encoder']);e.w_c.data.copy_(g['w_c']);e.b_c.data.copy_(g['b_c']);e.eval();x=load_executor();x.eval();cb=x.token_embedding(torch.arange(VALUE_BASE,VALUE_BASE+VALUE_COUNT));rows=[]
 for p in [z for z in m['test'] if z['order']=='reverse']:
  names=p['tokens'];d=e(torch.tensor([[e.vocab.encode_name(n) for n in names]]),torch.tensor([5]),return_details=True);rf,ra,_,af,aa,k,sf,sa,vt,c,vtg=d;ok=torch.where(c[0]>.5)[0];jf=ok[torch.argmax(2.5*sf[0,ok])];ja=ok[torch.argmax(2.5*sa[0,ok])];lf=x.register_decoder(torch.cat((vtg[0,jf].unsqueeze(0),torch.zeros((1,32))),-1),cb)[0];la=x.register_decoder(torch.cat((vtg[0,ja].unsqueeze(0),torch.zeros((1,32))),-1),cb)[0];df=int(lf.argmax());da=int(la.argmax());cf=int(x.register_decoder(cb[df].unsqueeze(0),cb)[0].argmax());ca=int(x.register_decoder(cb[da].unsqueeze(0),cb)[0].argmax());l=int(p['lower']);f=int(p['forbidden']);al=f'ARG_{next(i for i,v in enumerate(m["permutation"]) if v==l):02d}';afn=f'ARG_{next(i for i,v in enumerate(m["permutation"]) if v==f):02d}';uf=lf.topk(2).values;ua=la.topk(2).values;rows.append({'digest':p.get('digest'),'pointer_F':names[int(jf)]==al,'pointer_A':names[int(ja)]==afn,'decode_F':df==l,'decode_A':da==f,'RAW':df==l and da==f,'CANON':cf==l and ca==f,'RAW_CANON':df==cf and da==ca,'margin_F':float(uf[0]-uf[1]),'margin_A':float(ua[0]-ua[1]),'decoded_F':df,'decoded_A':da})
 s={k:sum(r[k] for r in rows) for k in ('pointer_F','pointer_A','decode_F','decode_A','RAW','CANON','RAW_CANON')};s.update({'cases':len(rows),'margin_F_positive':sum(r['margin_F']>0 for r in rows),'margin_A_positive':sum(r['margin_A']>0 for r in rows)});res={'status':'passed' if all(v==992 for k,v in s.items() if k!='cases') else 'failed','manifest_sha256':sha(M),'stage_a_sha256':sha(A),'gate_sha256':sha(G),'threshold':.5,'gamma':2.5,'tie_policy':'first/min-position','summary':s,'failures':[r for r in rows if not(r['pointer_F'] and r['pointer_A'] and r['decode_F'] and r['decode_A'] and r['RAW'] and r['CANON'] and r['RAW_CANON'] and r['margin_F']>0 and r['margin_A']>0)]};O.mkdir(exist_ok=True);(O/'results.json').write_text(json.dumps(res,indent=2)+'\n');print(json.dumps(res,indent=2))
if __name__=='__main__':main()
