import hashlib,json
from pathlib import Path
import torch
from nb5_fresh import NB5CoreEncoder,NB5GateOnlyEncoder
from ctrl2_common import load_executor
from evaluate_u0c_c1_e_r_alu import VALUE_BASE,VALUE_COUNT
R=Path(__file__).resolve().parents[1];M=R/'campaign/nb5_manifests/manifest_6801.json';A=R/'campaign/nb5_stage_a_6801/stage_a.pt';G=R/'campaign/nb5_stage_b_6801/gate.pt';O=R/'campaign/nb5_p_6801_joint'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 m=json.loads(M.read_text()); assert sha(M)=='de2b47cbd183c871a539ebc019232a8e5130e2a8ce582088eadc1b7c1d1b0244'; ae=torch.load(A,map_location='cpu',weights_only=False); gp=torch.load(G,map_location='cpu',weights_only=False); e=NB5GateOnlyEncoder(ae['encoder']); e.w_c.data.copy_(gp['w_c']);e.b_c.data.copy_(gp['b_c']);e.eval(); exe=load_executor();exe.eval(); cb=exe.token_embedding(torch.arange(VALUE_BASE,VALUE_BASE+VALUE_COUNT)); rows=[]
 for p in m['test']:
  names=p['tokens']; ti=torch.tensor([[e.vocab.encode_name(n) for n in names]]); le=torch.tensor([5]); d=e(ti,le,return_details=True);rf,ra,_,af,aa,k,sf,sa,vt,c,vtg=d; valid=c[0]>.5; gamma=2.5; eligible=torch.where(valid)[0]; jf=eligible[torch.argmax((gamma*sf[0,eligible]))]; ja=eligible[torch.argmax((gamma*sa[0,eligible]))]; qf=vtg[0,jf].unsqueeze(0);qa=vtg[0,ja].unsqueeze(0); lf=exe.register_decoder(torch.cat((qf,torch.zeros_like(qf)),-1),cb)[0];la=exe.register_decoder(torch.cat((qa,torch.zeros_like(qa)),-1),cb)[0]; df=int(lf.argmax());da=int(la.argmax()); topf=lf.topk(2).values;topa=la.topk(2).values; cf=int(exe.register_decoder(cb[df].unsqueeze(0),cb)[0].argmax());ca=int(exe.register_decoder(cb[da].unsqueeze(0),cb)[0].argmax()); l=int(p['lower']);f=int(p['forbidden']); expected_floor_token=f'ARG_{next(i for i,x in enumerate(m["permutation"]) if x==l):02d}';expected_avoid_token=f'ARG_{next(i for i,x in enumerate(m["permutation"]) if x==f):02d}'; rec={'order':p['order'],'digest':p.get('digest'),'L':l,'F':f,'pointer_F':names[int(jf)]==expected_floor_token,'pointer_A':names[int(ja)]==expected_avoid_token,'decode_F':df==l,'decode_A':da==f,'RAW':df==l and da==f,'CANON':cf==l and ca==f,'RAW_CANON':df==cf and da==ca,'margin_F':float(topf[0]-topf[1]),'margin_A':float(topa[0]-topa[1]),'pointer_margin_F':float((gamma*sf[0,eligible]).topk(2).values.diff().abs().item()),'pointer_margin_A':float((gamma*sa[0,eligible]).topk(2).values.diff().abs().item()),'decoded_F':df,'decoded_A':da,'pointer_token_F':names[int(jf)],'pointer_token_A':names[int(ja)]};rows.append(rec)
 summary={}
 for order in ('natural','reverse'):
  z=[r for r in rows if r['order']==order];summary[order]={'cases':len(z),'pointer_F':sum(r['pointer_F'] for r in z),'pointer_A':sum(r['pointer_A'] for r in z),'decode_F':sum(r['decode_F'] for r in z),'decode_A':sum(r['decode_A'] for r in z),'RAW':sum(r['RAW'] for r in z),'CANON':sum(r['CANON'] for r in z),'RAW_CANON':sum(r['RAW_CANON'] for r in z),'margin_F_positive':sum(r['margin_F']>0 for r in z),'margin_A_positive':sum(r['margin_A']>0 for r in z),'pointer_margin_F_positive':sum(r['pointer_margin_F']>0 for r in z),'pointer_margin_A_positive':sum(r['pointer_margin_A']>0 for r in z)}
 result={'status':'passed' if all(v==992 for s in summary.values() for k,v in s.items() if k not in ('cases',)) else 'failed','task':'NB5-P-6801-JOINT','manifest_sha256':sha(M),'stage_a_sha256':sha(A),'gate_sha256':sha(G),'gamma':2.5,'threshold':0.5,'tie_policy':'first/min-position','ground_truth_arguments_in_forward':False,'teacher_in_inference':False,'summary':summary,'failures':[r for r in rows if not all((r[k] if k in r else True) for k in ('pointer_F','pointer_A','decode_F','decode_A','RAW','CANON','RAW_CANON')) or r['margin_F']<=0 or r['margin_A']<=0],'cases':rows};O.mkdir(parents=True,exist_ok=True);(O/'results.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items() if k not in ('cases','failures')},indent=2))
if __name__=='__main__':main()
